<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'hllizi\\phpmonads\\arraymonad' => '/ArrayMonad.php',
                'hllizi\\phpmonads\\illicitvalueexception' => '/IllicitValueException.php',
                'hllizi\\phpmonads\\incompatibletypeexception' => '/IncompatibleTypeException.php',
                'hllizi\\phpmonads\\maybemonad' => '/MaybeMonad.php',
                'hllizi\\phpmonads\\monadinterface' => '/MonadInterface.php',
                'hllizi\\phpmonads\\monadtrait' => '/MonadTrait.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
